sonar.organization=jbcom
sonar.projectKey=jbcom_seeded-maze
sonar.projectName=seeded-maze
sonar.sources=src
sonar.tests=src
sonar.exclusions=**/*.test.ts,dist/**,docs/**,examples/**
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
